function H(a,f,b){function k(){0!=L&&(O=(new Date).getTime()-L)}function n(e){G=G|e;A.narme=G}function p(e){q.a("l2("+e+")");C=C|e;V()?(k(),L=0):0==L&&(L=(new Date).getTime());A.narm=C;q.a("l2e")}function r(e){P=P|e;A.naral=P}var q=new S,t=b&&b.dvObj||window.$dv,c=b&&"undefined"!==typeof b.billable||t&&t.tags[$uid]&&t.tags[$uid].billable,m=b&&b.impressionId||window.$uid,l=window.Nf||f,w=Array(l.kb),h=l.$a/l.ac+1,d=null,e="",g={},v=0,x,z,D=Array(l.kb),u={fa:{I:null,J:null,F:null,D:null,Me:!1},i:{u:null,
s:null,K:null,L:null,G:null,H:null,o:null,m:null,Me:!1},wa:{Cb:null,Bb:null},Ib:0},E={},F={},J,K,y={},M={},N=null;this.Fb=function(e){if(null==N||1==N||8==N)N=e};for(f=0;f<l.kb;f++)D[f]="b"+f;var B={};b&&t&&t.CommonData&&(B.ctx=b.mb,B.cmp=b.lb,B.btreg=b.btreg,B.btadsrv=b.Ua,B.uid=b.rb,B.brid=t.CommonData.BrowserId,B.brver=t.CommonData.BrowserVersion,B.tstype=t.CommonData.Scenario);B.jsver=a?a:null;var A={},I={},L=0,O="",Q="",P=0,C=0,G=0,R=0;this.Pc=function(){return L};this.pd=function(e){R=R|e;A.vct=
R};this.od=function(e){d=e;I.strp=d;this.od=function(){}};this.dc=function(){return(new Date).getTime()};var W=this.dc();this.Ce=function(){return W};this.ef=function(){C=C&-3;G=G&-2;G&=-3};this.Eb=function(){p(2)};this.rf=function(){n(8);this.qc()};this.qc=function(){p(4)};this.kd=function(){r(8);this.Eb()};this.vd=function(e){r(16);A.dbg9=e};this.wd=function(){r(1)};this.pf=function(){this.Eb();n(1)};this.nf=function(){this.Eb();n(2)};this.cb=function(e,g){p(8);Q=q.ve(e,g)};this.kf=function(){q.a("l1");
C=C&-3;p(1);q.a("l1e")};this.nd=function(){p(16)};this.pe=function(){return w};this.ld=function(e,g){m=m||b&&b.impressionId||window.$uid;var c;try{m&&t&&t.tags[m]&&t.tags[m].getTimeDiff&&(c=t.tags[m].getTimeDiff())}catch(d){}var a=c-x||100;x=c;z?200>z.length&&z.push(a):z=[];q.a("ie15");0<=e.g&&(c=Math.floor(e.g/l.ac),0<e.g%l.ac?c++:0<e.g&&c++,isNaN(w[c])&&(w[c]=0),w[c]+=Math.max(g,a),e.M&&c>=h||0==e.M&&6<=c?v+=Math.max(g,a):(timeStampTotalBuckets=v=0,this.Fb(7)));q.a("ie15e")};this.mf=function(e){var g=
e.Xc;null!=e.Xc&&(E.advisonl=g);null!=e.Wc&&(E.adabvvponl=e.Wc);A.dbg8="CSS1Compat"===document.compatMode?1:0;q.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(A.dbg10=document.documentMode);q.a("ff52e")};this.bb=function(e){q.a("ie14");null!=e&&(M.adbtftopg=e)};this.lf=function(e){null!=e&&(u=e)};this.md=function(e){q.a("ie19");this.lf(e.B);this.tf();q.a("ie19e")};this.zd=function(){null!=u.fa.I&&(y.vptoscrx=Math.round(u.fa.I));null!=u.fa.J&&(y.vptoscry=Math.round(u.fa.J));
null!=u.fa.F&&(y.vpwdth=Math.round(u.fa.F));null!=u.fa.D&&(y.vphgt=Math.round(u.fa.D));null!=u.i.u&&(y.adtovpx=Math.round(u.i.u));null!=u.i.s&&(y.adtovpy=Math.round(u.i.s));null!=u.i.K&&(y.adtopgx=Math.round(u.i.K));null!=u.i.L&&(y.adtopgy=Math.round(u.i.L));null!=u.i.G&&(y.adtoscrx=Math.round(u.i.G));null!=u.i.H&&(y.adtoscry=Math.round(u.i.H));null!=u.wa.Cb&&(y.scrwdth=Math.round(u.wa.Cb));null!=u.wa.Bb&&(y.scrhgt=Math.round(u.wa.Bb));y.almesind=u.Ib};this.Ad=function(){if(J&&K){var e=null!=u.i.o?
u.i.o:null,g=null!=u.i.m?u.i.m:null;0>J*K&&(F.dvp_adwdth=J,F.dvp_adhgt=K,J=e,K=g)}else J=null!=u.i.o?u.i.o:null,K=null!=u.i.m?u.i.m:null;null!=J&&(F.adwdth=J);null!=K&&(F.adhgt=K)};this.tf=function(){k();for(var e=0;e<w.length;e++)w[e]&&(g[D[e]]=w[e]);this.zd();this.Ad();q.v(y,E);q.v(y,F);q.v(y,M)};this.Nc=function(){if(1E3<=v)return!0;this.Fb(8);return!1};this.ze=function(h){var d={};m=m||b&&b.impressionId||window.$uid;var l=-1,a=q.we();try{t&&t.tags[m]&&t.tags[m].getTimeDiff&&(l=t.tags[m].getTimeDiff())}catch(v){}var w=
[];q.v(d,B);switch(h){case 1:e=l;q.v(d,I);q.v(d,A);d.napt=O;q.v(d,y);d.dvp_log=a;d.napr=Q;c&&(d.isbmms=l,b.zb||(d.isbmms=l,d.isgmmims=l));d.ismms=e;d.isumms=l;break;case 2:q.v(d,I);q.v(d,A);d.napt=O;q.v(d,y);d.dvp_log=a;d.napr=Q;d.isnmms=l;break;case 3:d.istoms=l,d.nvr=N;case 4:case 8:q.v(d,I);q.v(d,M);q.v(d,F);d.isbxdms=l;q.v(d,g);d.nvr=N;break;case 5:q.v(d,I);q.v(d,M);q.v(d,F);q.v(d,E);d.ismms=e||l;d.isiabvms=l;d.isuiabvms=l;break;case 6:q.v(d,M);q.v(d,F);q.v(d,E);d.ismms=e||l;d.iscvmvms=l;break;
case 16:q.v(d,I);q.v(d,A);d.napt=O;d.dvp_log=a;d.napr=Q;d.ishems=l;break;case 7:return w.join("");case 17:q.v(d,I);q.v(d,M);q.v(d,F);d.isbmms=l;d.isbvms=l;b.zb||(d.isgmmims=l,d.isgmpims=l);break;default:q.v(d,I),q.v(d,g),q.v(d,A),q.v(d,E),d.napt=O,d.dvp_log=a,d.napr=Q}d.evid=h;d.ctime=this.dc();return d};this.oe=function(){q.a("ie17");for(var e=[],g=0;g<l.kb;g++)e[g]=w[g]?w[g]:0;return e};var V=this.Hc=function(){return 2==(C&2)&&8!=(P&8)||4==(C&4)||8==(G&8)&&8==(P&8)?!1:!0};this.af=function(e){q.a("l3");
e=q.da(e);q.a("cm3e");e&&(A.dbg5=e.w,A.dbg6=e.h);q.a("l3e")};return this}function T(a,f){var b=new S,k=a&&a.impressionId||window.$uid;this.aa=function(a,p){if(f){var r=f.ze(a);p&&b.v(r,p);var q=!1,t=0;4==a||8==a?q=!0:b.za("crto")&&(t=b.za("crto"));this.jd(k,r,t,q)}};this.jd=function(a,f,b,k){$dv&&$dv.registerEventCall&&a&&(b?$dv.registerEventCall(a,f,b,!0,k):$dv.registerEventCall(a,f,null,null,k))}}function U(){this.aa=function(){};this.jd=function(){}}
function X(a,f,b,k){function n(){if(1==x){try{for(var e in g)v.removeChild(g[e]);d.document.body.removeChild(v)}catch(h){}x=!1}}function p(e){e=e||0;var g=t(0);g.$c()?7<g.qb()?(n(),D=z=x=!1):(x=!0,z=!1):20>e?(e++,setTimeout(p,50,e)):(x=z=D=!1,n())}function r(e){$dv&&$dv.tags&&$dv.tags[k]&&$dv.tags[k].getTimeDiff&&$dv.tags[k].getTimeDiff();if(null!==e.ib)for(var g=0;g<e.ib.length;g++){var d=t(g).qb();0==g?d>u&&(u=d):d>E&&(E=d)}}function q(e){for(var g=!0,d=0;13>=d;d++)var h=t(d),g=g&(null!==h&&h.$c());
if(!g)return null;e.Dc=0;e.oc=0;e.nc=0;e.ic=0;e.Ea=0;e.ib=Array(13);g=t(0).qb();for(d=1;13>=d;d++)if(h=5<Math.abs(t(d).qb()-g),e.ib[d]=h)switch(e.Dc++,d){case 2:case 3:case 4:case 5:e.oc++;break;case 6:case 7:case 8:case 9:e.nc++;break;case 10:case 11:case 12:case 13:e.ic++}if(13===e.Dc)return e.Ea=100,r(e),!0;g=e.ib;if(!1===g[1]){if(3<=e.ic||3<=e.nc||3<=e.oc)return r(e),null;e.Ea=0;r(e);return!1}if(!0===g[1]&&(!0===g[2]&&!0===g[3]||!0===g[2]&&!0===g[4]||!0===g[3]&&!0===g[5]||!0===g[4]&&!0===g[5])||
!0===g[1]&&4==e.nc||!0===g[1]&&4==e.ic&&1<=e.oc)return e.Ea=50,r(e),!0;if(g[2]&&g[5]&&!(g[6]&&g[10]&&g[1]&&g[13]&&g[9])||g[4]&&g[3]&&!(g[8]&&g[12]&&g[1]&&g[11]&&g[7]))return r(e),null;e.Ea=0;r(e);return!1}function t(e){e=g[e];var d=null;e&&(d=e.contentWindow);return d}function c(){for(var d=e.getBoundingClientRect(),h=d.width,c=d.height,m=h/(1+l),a=c/(1+l),v=h/l,x=c/l,f=0;13>=f;f++){var b=d.left,k=d.top;switch(f){case 0:k=b=-1E5;break;case 1:b+=(h-w)/2;k+=(c-w)/2;break;case 3:b+=h-w;break;case 4:k+=
c-w;break;case 5:b+=h-w;k+=c-w;break;case 6:b+=(h-v)/2;k+=(c-x)/2;break;case 7:b+=(h-v)/2+v;k+=(c-x)/2;break;case 8:b+=(h-v)/2;k+=(c-x)/2+x;break;case 9:b+=(h-v)/2+v;k+=(c-x)/2+x;break;case 10:b+=(h-m)/2;k+=(c-a)/2;break;case 11:b+=(h-m)/2+m;k+=(c-a)/2;break;case 12:b+=(h-m)/2;k+=(c-a)/2+a;break;case 13:b+=(h-m)/2+m,k+=(c-a)/2+a}6<=f&&(b-=w/2,k-=w/2);var n=g[f];n.style.left=b+"px";n.style.top=k+"px"}}function m(){if(null!=e&&null!=e.parentNode){z=!0;v=d.document.createElement("div");d.document.body.appendChild(v);
for(var h=0;13>=h;h++){var l=d.document.createElement("iframe");l.width=w;l.height=w;l.style.position="absolute";l.frameBorder="0";l.style.visibility="hidden";l.style.zIndex=-9999999;l.style.display="block";l.src="javascript:no=false;yes=true;("+function(){window.Ue={Yd:100};window.Kc=no;window.gb=0;window.Lc=0;window.Vc=0;window.Of=no;window.qb=function(){return window.Vc};window.$c=function(){return window.Kc};window.Se=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Vb=function(){window.gb++;window.Se(window.Vb,document)};window.Vb();setInterval(function(){10>window.gb&&window.Vb();window.Vc=window.gb-window.Lc;window.Lc=window.gb},window.Ue.Yd);window.setTimeout(function(){window.Kc=yes},250)}.toString()+")();";v.appendChild(l);g.push(l)}c()}}var l=Math.sqrt(2),w=1,h=new S,d=null,e=null,g=[],v,x=!1,z=!1,D=h.xb(a,f,b);0==h.Ya()&&(w=8);var u=0,E=0;this.Je=function(){0==z&&(0==(this.Za()&&(null!=e&&h.Zc(e,d)?!0:!1))?x=!1:(m(),
p()))};this.Za=function(){return D};this.Pe=function(){return x};this.qd=function(g,h){d=g;e=h;this.Je()};this.Fe=function(){if(0==x)return null;var e={};return null==q(e)?null:e.Ea}}
function aa(a,f,b,k,n,p,r,q){this.b=new S;this.window=a;this.c=f;this.R=b;this.N=k;this.Z=r&&r.Enums.BrowserId||window.$dv.Enums.BrowserId;this.W=r&&r.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.O=n;this.hc=p;this.ha=null;this.Uc=this.window?this.b.yb(this.window.top):this.b.yb(window.top);this.Le=this.R!=this.W.CrossDomain&&this.b.za("ofs")&&this.Uc;this.ha=new X(this.R,this.N,r,q);null!=this.ha&&this.ha.Za()&&this.ha.qd(this.window,this.c);this.tb=this.Ab=this.ra=null;this.ub=!1;
var t=0;this.ia={Md:1,Nd:2,Gd:4,Nb:8,Fd:16,Ob:32,Ld:64};this.pc=function(c,m,l,a){if(a&&a.insertBefore&&a.firstChild&&(c=this.window.document.createElement(c))){for(var h in m)c[h]=m[h];for(h in l)c.style[h]=l[h];a.insertBefore(c,a.firstChild);return c}return null};this.me=function(c,a,l){var b=this.window.top,h=c.width,d=c.height;0>l.left?(h=c.width-Math.abs(l.left),0>a.Ca&&(h-=Math.abs(a.Ca))):0>a.Ca&&(h=c.width-Math.abs(a.Ca)+l.left,h=h>c.width?c.width:h);var e=c.width,g=Math.min(this.b.Aa(b.window).clientWidth,
b.innerWidth),v=screen.availWidth-g-a.Ca,x=0;h<e?(e=h,x=g-h,0>a.Ca&&(x-=Math.abs(a.Ca))):x=g-e-l.left;0>x?(h=e-Math.abs(x),0>v&&(h-=Math.abs(v))):0>v&&(h=e-Math.abs(v)+x,h=h>e?e:h);a=screen.availHeight-a.ff-b.outerHeight;b=Math.min(this.b.Aa(b.window).clientHeight,b.innerHeight)-c.height-l.top;0>b?(d=c.height-Math.abs(b),0>a&&(d-=Math.abs(a))):0>a&&(d=c.height-Math.abs(a)+b,d=d>c.height?c.height:d);0>l.top&&(d-=Math.abs(l.top));return{yf:h,zf:d}};this.cc=function(c,a,l,b){var h=l.F,d=l.D,e=0;l=0;
var g={width:a.right-a.left,height:a.bottom-a.top};if(0>a.bottom||0>a.right||a.top>d||a.left>h||0>=g.width||0>=g.height)return 0;0>a.top?Math.abs(a.top)>=g.height?e=g.height:(e=g.height+a.top,e>d&&(e=d)):e=a.top+g.height>d?d-a.top:g.height;0>a.left?Math.abs(a.left)>=g.width?l=g.width:(l=g.width+a.left,l>h&&(l=h)):l=a.left+g.width>h?h-a.left:g.width;this.Le&&(c=this.me(g,c,a),l=c.yf,e=c.zf);return 0>=l||0>=e?0:Math.round(l*e/(g.width*g.height)*(b?g.width*g.height/((b.right-b.left)*(b.bottom-b.top)):
1)*100)};this.bc=function(c,a){try{var l={x:c.offsetLeft,y:c.offsetTop},b;c.offsetParent?(b=this.bc(c.offsetParent,a),l.x+=b.x,l.y+=b.y):a!=a.parent&&this.b.Pb(a,a.parent)&&(b=this.bc(a.frameElement,a.parent),l.x+=b.x,l.y+=b.y);return l}catch(h){return{x:null,y:null}}};this.na=function(c){if(this.R==this.W.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.na=function(){var e=this.b.Na(this.window),d=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(e.win.h):this.O.Explorer.X,h={F:null,D:null,I:null,J:null,j:!1};h.F=parseInt(e.win.w);h.D=parseInt(e.win.h);h.I=parseInt(e.win.l);h.J=parseInt(e.win.t)+d;h.j=!0;return h};else if(this.N.Y==this.Z.Firefox)this.na=function(){var e=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,d=e?0:this.window.screenX-screen.left,e=e?0:this.window.screenY-screen.top,h={F:null,D:null,I:null,J:null,j:!1};h.F=this.window.outerWidth;h.D=this.window.outerHeight-this.O.Firefox.X;h.I=d;h.J=
e+this.O.Firefox.X;h.j=!0;return h};else if(this.b.kc(this.window)){var a=this;this.window.context.observeIntersection(function(e){e.forEach(function(e){a.ra=e})});this.na=function(){var e={F:null,D:null,j:!1,I:null,J:null};null!=this.ra?(e.F=this.ra.rootBounds.width,e.D=this.ra.rootBounds.height):(e.F=0,e.D=0);e.j=!0;return e}}else if(this.N.Y==this.Z.IE&&/^[11|12]/.test(this.N.ta))this.na=function(){var e=-8==this.window.screenY&&-8==this.window.screenX,d=e?0:this.window.screenX,e=e?0:this.window.screenY,
h={F:null,D:null,I:null,J:null,j:!1};h.F=this.window.outerWidth;h.D=this.window.outerHeight-this.O.Explorer.X;h.I=d;h.J=e+this.O.Explorer.X;h.j=!0;return h};else if(this.N.Y==this.Z.IE&&/[6-9]|[10]/.test(this.N.ta)){var l=this.pc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,he:0,Ve:"0",We:"0"},{display:"inline",position:"absolute",top:0,left:0,xf:"none",zIndex:0,border:0},this.window.document.body),b=this.pc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,he:0,Ve:"0",We:"0"},{display:"inline",
position:"absolute",top:0,left:0,xf:"none",zIndex:0,border:0},this.window.document.body),h=b.contentWindow||b.window||b.contentDocument.window||b.contentWindow.window||this.window.Cf,d=l.contentDocument||l.contentWindow.document,l=b.contentDocument||b.contentWindow.document,e="<html><head><script >window.onload = "+function(e){e&&(window.event=e);isFinite(String(window.event.clientY))&&(parent.Va={Sb:window.event.clientY,Rb:window.event.clientX,yd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",b='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(e){e&&(window.event=e);isFinite(String(window.event.clientY))&&(parent.sa={Sb:window.event.clientY,Rb:window.event.clientX,Ia:window.event.screenY-window.event.y,Ha:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";l.open("text/html","replace");l.write(b);l.close();
d.open("text/html","replace");d.write(e);d.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.na=function(){h.runMoM();d.open("text/html","replace");d.write(e);d.close();var g=this.window.sa,c=this.window.Va,a=screen.availWidth,l=screen.availHeight,c=c?c.yd:this.O.Explorer.X;if(g){var b=g.Ha,m=g.Ia;g.Ha>=a&&(g.Ha-=a);g.Ia>=l&&(g.Ia-=l);var f={F:null,D:null,I:null,J:null,j:!1};f.F=this.window.outerWidth?this.window.outerWidth-
20:a-g.Ha-20;f.D=this.window.outerHeight?this.window.outerHeight-c-10:l-g.Ia-10;f.I=b;f.J=m;f.j=!0}else f={F:null,D:null,I:null,J:null,j:!1},f.F=this.window.outerWidth?this.window.outerWidth-20:a-20,f.D=this.window.outerHeight?this.window.outerHeight-c-10:l-10,f.I=null,f.J=null,f.j=!1;return f}}else this.b.wb()?(this.gd(),this.na=function(){this.ub||this.gd();var e={F:null,D:null,I:null,J:null,j:!1};e.F=this.window.outerWidth;e.D=this.window.outerHeight-this.O.Chrome.X;e.j=!1;return e}):this.na=this.N.Y==
this.Z.Chrome?function(){var e={F:null,D:null,I:null,J:null,j:!1},d=!1;try{e.F=this.window.frameElement.offsetParent.parentNode.clientWidth,e.D=this.window.frameElement.offsetParent.parentNode.clientHeight,d=!0}catch(h){}e.I=this.window.screenX;e.J=this.window.screenY;e.j=d;return e}:null!=this.ha&&this.ha.Za()?function(){var e={F:null,D:null,I:null,J:null,j:!1};e.F=this.window.outerWidth;e.D=this.window.outerHeight-this.O.Safari.X;e.j=!1;return e}:function(){return{F:null,D:null,I:null,J:null,j:!1}};
else this.na=function(){var e,d,h=this.window.top;void 0!=h.mozInnerScreenX&&null!=h.mozInnerScreenX?(e=h.mozInnerScreenX,d=h.mozInnerScreenY):void 0!=h.screenX&&null!=h.screenX?0!=h.screenLeft+8&&h.screenLeft+8!=screen.width||0!=h.screenTop+8&&h.screenTop+8!=screen.height?(e=h.screenLeft,d=h.screenTop+(h.outerHeight-h.innerHeight)):(e=h.screenLeft+8,d=h.screenTop+(h.outerHeight-h.innerHeight)+8):(e=h.screenLeft,d=h.screenTop);var c={F:null,D:null,I:null,J:null,j:!1},a=this.b.Aa(h);c.F=h.innerWidth||
a.clientWidth;c.D=h.innerHeight||a.clientHeight;c.I=e;c.J=d;c.j=!0;return c};return this.na(c)};this.la=function(c,a){t=1;this.R==this.W.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.Na(this.window).par?(t=8,this.la=function(){var c=this.b.Na(this.window),a=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.O.Explorer.X,h={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};
h.u=parseInt(c.self.l)-parseInt(c.par.l);h.s=parseInt(c.self.t)-parseInt(c.par.t);h.K=parseInt(c.self.l);h.L=parseInt(c.self.t);h.G=parseInt(c.win.l)+h.u;h.H=parseInt(c.win.t)+h.s+a;h.o=parseInt(c.self.w);h.m=parseInt(c.self.h);h.j=!0;h.rect={top:h.s,bottom:h.s+h.m,left:h.u,right:h.u+h.o};return h}):this.N.Y==this.Z.Firefox?this.la=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var a=this.window.screenX,h=this.window.screenY,d=this.window.mozInnerScreenX/c-a,c=this.window.mozInnerScreenY/
c-h-this.O.Firefox.X,d={left:d,top:c,right:d+this.window.innerWidth,bottom:c+this.window.innerHeight},c={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};c.u=d.left;c.s=d.top;c.K=null;c.L=null;c.G=a+d.left;c.H=h+d.top;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.j=!0;c.rect=d;this.b.Hb()&&(c=this.ob(c));return c}:this.b.kc(this.window)?(t=32,this.la=function(){var c={u:null,s:null,o:null,m:null,j:!1,rect:null,P:null,qa:null,K:null,L:null,G:null,H:null};
null!=this.ra?(c.u=this.ra.boundingClientRect.left,c.s=this.ra.boundingClientRect.top,c.o=this.ra.boundingClientRect.width,c.m=this.ra.boundingClientRect.height):(c.u=0,c.s=0,c.o=0,c.m=0);c.j=!0;c.rect={top:c.s,bottom:c.s+c.m,left:c.u,right:c.u+c.o};return c}):this.N.Y==this.Z.IE&&/^[11|12]/.test(this.N.ta)?this.la=function(c){var a=this.window.screenLeft-window.screenX,h=this.window.screenTop-window.screenY-this.O.Explorer.X,a={left:a,top:h,right:a+this.window.innerWidth,bottom:h+this.window.innerHeight},
h={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};h.u=a.left;h.s=a.top;h.K=null;h.L=null;h.G=c.I+a.left;h.H=c.J+a.top;h.o=this.window.innerWidth;h.m=this.window.innerHeight;h.j=!0;h.rect=a;this.b.Hb()&&(h=this.ob(h));return h}:this.N.Y==this.Z.IE&&/[6-9]|[10]/.test(this.N.ta)?this.la=function(){if(8==document.documentMode)return{u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};var c=this.window.Va&&this.window.sa?this.window.Va.Sb-
this.window.sa.Sb:0,a=this.window.Va&&this.window.sa?this.window.Va.Rb-this.window.sa.Rb:0,h=this.b.Aa(this.window),d={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};d.u=a;d.s=c;d.K=null;d.L=null;d.G=this.window.sa?a+this.window.sa.Ha:null;d.H=this.window.sa?c+this.window.sa.Ia:null;d.o=this.window.innerWidth||h.clientWidth;d.m=this.window.innerHeight||h.clientHeight;d.j=!0;d.rect={left:a,top:c,right:a+(this.window.innerWidth||h.clientWidth),bottom:c+(this.window.innerHeight||
h.clientHeight)};this.b.Hb()&&(d=this.ob(d));return d}:this.b.wb()?(t=512,this.la=function(){var c={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};null!=this.c&&(adData=this.b.pb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}):this.la=this.N.Y==this.Z.Chrome?function(){var c=null,a=null,h=!1;try{var d=this.window.frameElement.offsetTop,c=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
a=d-this.window.frameElement.offsetParent.scrollTop,h=!0}catch(e){}d={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null};d.u=c;d.s=a;d.K=null;d.L=null;d.G=null;d.H=null;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.j=h;d.rect=h?{left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight}:null;this.b.Hb()&&(d=this.ob(d));return d}:null!=this.ha&&this.ha.Za()?function(){var c={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,
rect:null,P:null,qa:null};null!=this.c&&(adData=this.b.pb(this.c),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}:function(){return{u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null}}:this.la=function(c){var a=this.bc(this.c,this.window),h={u:null,s:null,K:null,L:null,G:null,H:null,o:null,m:null,j:!1,rect:null,P:null,qa:null},d=this.b.ec(this.c,this.window),e=this.b.wc(this.c,this.window);h.u=e.left;h.s=e.top;h.K=
a.x;h.L=a.y;h.G=c.I+e.left;h.H=c.J+e.top;h.o=e.w;h.m=e.h;h.j=!0;h.rect=d;h.P=e;return h};return this.la(c,a)};this.ob=function(c){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return c;var a=this.b.pb(this.c);if(a){var b=a.w,f=a.h,h=c.u,d=c.s,e=c.H,g=c.G;null!=c.u&&null!=c.s&&null!=c.m&&null!=c.o&&c.rect&&(0<a.t?(d=c.s+a.t,null!=c.H&&(e=c.H+a.t)):f+=a.t,0<a.l?(h+=a.l,null!=c.G&&(g=c.G+a.l)):b+=a.l,a.r>c.o&&(b-=a.r-c.o),a.Cc>c.m&&(f-=a.Cc-c.m),c.o=0<b?b:0,c.m=0<
f?f:0,c.u=h,c.s=d,c.H=e,c.G=g,c.rect.left=c.u,c.rect.top=c.s,c.rect.right=c.u+a.w,c.rect.bottom=c.s+a.h,c.P={w:b,h:f,left:h,right:h+b,top:d,bottom:d+f})}return c};this.Be=function(){var c=screen.availWidth,a=screen.availHeight,b=screen.width,f=screen.height,h=0,d=0;this.Uc&&(d=this.window.top,h=d.screenX,d=d.screenY);return{j:this.O.Ya?!1:"undefined"!==typeof h,Cb:c||b,Bb:a||f,Lf:h,Mf:d,Ca:h-(b-c),ff:d-(f-a)}};this.ke=function(){var c=this.Be(),a=this.na(c),b=this.la(a,c);return{fa:a,i:b,wa:c,Ib:(null==
a.I||null==a.J?0:this.ia.Md)|(null==a.F||null==a.D?0:this.ia.Nd)|(null==b.u||null==b.s?0:this.ia.Gd)|(null==b.K||null==b.L?0:this.ia.Nb)|(null==b.G||null==b.H?0:this.ia.Fd)|(null==b.m||null==b.o?0:this.ia.Ob)|(null==c.Bb||null==c.Cb?0:this.ia.Ld),M:this.Wb(b.m,b.o)}};this.Wb=function(c,a,b){null==c&&(c=0);null==a&&(a=0);return 1!=this.O.Ya||b?242500<=c*a:!1};this.se=function(){this.b.a("c10");if(null!=this.c)if(this.b.Zc(this.c,this.window))try{var c={timeStamp:new Date,g:-3,ja:-3,B:null,M:!1,ga:0};
if(!this.hc())return c;var a=this.ke(),b;if(!a.i.j||!a.fa.j){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return b=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,g:b,ja:b,B:a,M:a.M,ga:16};if(this.b.wb()&&this.ub)return b=0,null!=this.tb&&(b=Math.round(100*this.tb.intersectionRatio)),{timeStamp:new Date,g:b,ja:b,B:a,M:this.Wb(a.i.m,a.i.o),ga:512};if(this.ha.Za()){var f={timeStamp:new Date,g:-3,ja:-3,B:null,M:!1,ga:2};if(0==this.ha.Pe())f.g=-6,f.ja=-6,this.ha.qd(this.window,
this.c);else{var h=this.ha.Fe();null!=h&&(f.B=a,f.M=a.M,f.g=h,f.ja=h)}return f}c.B=a;t&&(c.ga=t);return c}if(a.i&&a.i.P&&(0===a.i.P.w||1===a.i.P.w||0===a.i.P.h||1===a.i.P.h))return{timeStamp:new Date,g:-5,ja:-5,B:a,ga:t};b=a.i.P?this.cc(a.wa,a.i.P,a.fa,a.i.rect):this.cc(a.wa,a.i.rect,a.fa);return{timeStamp:new Date,g:b,ja:b,B:a,M:a.M,ga:t}}catch(d){return{timeStamp:new Date,g:-4,ja:-4,B:null,M:!1,ga:t}}else return{timeStamp:new Date,g:-2,ja:-2,B:null,M:!1,ga:0};else return{timeStamp:new Date,g:-1,
ja:-1,B:null,M:!1,ga:0}};this.le=function(c,a){this.b.a("c11");var b=null,f=null;if(null!=c.B){var h=c.B.i;a<=this.O.Ye&&(b=0<=c.g||-5==c.g?c.M&&c.g>=this.O.$a||0==c.M&&50<=c.g?!0:!1:null,f=c.M?this.O.$a/100:.5,f=0==b?0>h.s+h.m*f?!0:!1:1==b?!1:null)}return{Wc:f,Xc:b}};this.vb=function(c){this.b.a("c12");var a=null;if(2!=c.ga&&512!=c.ga&&null!=c.B){var b=c.B.Ib,f=c.B.i;(b&this.ia.Nb)==this.ia.Nb&&(b&this.ia.Ob)==this.ia.Ob&&(a=this.cc(c.B.wa,{left:f.K,top:f.L,right:f.K+f.o,bottom:f.L+f.m},c.B.fa,f.rect),
a=0<=c.g?c.M&&a>=this.O.$a||0==c.M&&50<=a?!1:!0:null)}this.b.a("c12e");return a};this.gd=function(){function a(c){c.forEach(function(a){b.tb=a})}var b=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(t=512,this.Ab=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.Ab.observe(this.c),this.ub=!0)};this.Ie=function(){this.c=null;null!=this.Ab&&(this.Ab.disconnect(),this.tb=null,this.ub=!1)}}
function S(){this.getElementVolume_object=function(a){var f=a.getAttribute("width"),b=a.getAttribute("height");null==f||""==f||null==b||""==b?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:f,h:b};return a};this.Qe=function(a){var f=0;try{for(;null!=a&&10>f;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;f++}}catch(b){}return!0};this.da=function(a,f){this.a("cm1");var b=null,k=a.nodeName.toLowerCase();f&&this["getElementVolume_"+
k]&&(b=this["getElementVolume_"+k](a));if(!b&&(b=this.pb(a),this.a("cm2e"),!b||1>=b.w||1>=b.h))return this.a("cm1e"),{w:0,h:0};b.w.indexOf&&b.w.indexOf("px")&&(b.w=b.w.replace("px",""));b.h.indexOf&&b.h.indexOf("px")&&(b.h=b.h.replace("px",""));this.a("cm1e");return b};this.pb=function(a){this.a("cm2");try{var f;return document.body.getBoundingClientRect&&(f=a.getBoundingClientRect())?{w:f.right-f.left,h:f.bottom-f.top,l:f.left,t:f.top,Cc:f.bottom,r:f.right}:null}catch(b){return null}};this.Aa=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Oc=function(a,f){this.a("ff9");var b=0,k=!1;if(a.document.all)for(var n=0;n<a.document.all.length;n++)"BODY"==a.document.all[n].nodeName&&(k=!0),k&&("width"==f?a.document.all[n].width>b&&(b=a.document.all[n].width):a.document.all[n].height>b&&(b=a.document.all[n].height));this.a("ff9e");return b};this.bd=function(a,f){for(var b=this.Aa(a),k=a.innerWidth||b.clientWidth||this.Oc(a,"width"),b=a.innerHeight||b.clientHeight||this.Oc(a,"height"),n=f.length,
p=0,r=0;r<n;r++)if(15>=Math.abs(k-f[r].w)){p=f[r].h.length;for(k=0;k<p;k++)if(15>=Math.abs(b-f[r].h[k]))return!0;break}return!1};this.uf=function(a){for(var f=[],b=-1;f[++b]=a[b];);f.length--;return f};this.Kb=function(a,f,b,k){var n=a.getElementsByTagName("*"),n=this.uf(n);n.unshift(a);for(var p=["EMBED","IFRAME","OBJECT","IMG","DIV"],r=[],q=0;q<n.length;q++){var t=n[q];if(-1!=p.indexOf(t.nodeName)){var c=k(t);c&&r.push({Bc:c.w*c.h,w:c.w,h:c.h,type:t.nodeName||"other",ge:t})}}r=r.sort(function(a,
c){return c.Bc-a.Bc||p.indexOf(c.type)-p.indexOf(a.type)});(f=0<r.length&&r[0].w>f&&r[0].h>b?r[0].ge:null)&&a&&(f.sb=a.sb);return f};this.Zc=function(a,f){this.a("ff10");try{if(!a)return!1;for(f||(f=window);a!=f.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==f.document}catch(b){return!1}};this.ec=function(a,f){var b=f.parent,k={left:0,right:0,top:0,bottom:0};if(a){var n=a.getBoundingClientRect();f!=b&&this.Pb(f,b)&&(k=this.ec(f.frameElement,b));k={left:n.left+k.left,right:n.right+
k.left,top:n.top+k.top,bottom:n.bottom+k.top}}return k};this.Pb=function(a,f){var b=!1;if(a==f)b=!0;else try{a.document.domain==f.document.domain&&(b=!0)}catch(k){}return b};this.te=function(a){if(a)try{if(a.contentDocument&&this.Yc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.yb(a.contentWindow))return a.contentWindow.document}catch(f){}return null};this.Sc=function(a){return a?a.defaultView||a.parentWindow:null};this.Ke=function(a,f){return-1<f.indexOf(a)};this.ne=function(a){try{return a!=
a.top&&a.parent&&this.yb(a.parent)?a.parent:null}catch(f){return null}};this.yb=function(a){try{return a&&a.document&&this.Yc(a.document)?!0:!1}catch(f){return!1}};this.Yc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(f){return!1}};this.wc=function(a,f){var b=f.parent,k={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(k=this.ec(a,f),k.w=k.right-k.left,k.h=k.bottom-k.top,f!=b&&this.Pb(f,b)&&(b=this.wc(f.frameElement,b),b.bottom<k.bottom&&(b.bottom<k.top&&(k.top=b.bottom),
k.bottom=b.bottom),b.top>k.top&&(b.top>k.bottom&&(k.bottom=b.top),k.top=b.top),b.right<k.right&&(b.right<k.left&&(k.left=b.right),k.right=b.right),b.left>k.left&&(b.left>k.right&&(k.right=b.left),k.left=b.left),k.w=k.right-k.left,k.h=k.bottom-k.top));return k};this.Xb=function(a,f){return function(){return a.apply(f,arguments)}};this.ma=function(a){try{return a?a.length?a.length:0:0}catch(f){return 0}};this.gc=function(a){for(var f=[],b=0;b<a.length;b++)this.Qe(a[b])&&f.push(a[b]);return f};this.a=
function(a){try{maxLength=3,$dv&&($dv.Oa=$dv.Oa||[],$dv.Oa.push(a),$dv.Oa.length>maxLength&&$dv.Oa.shift())}catch(f){}};this.we=function(){try{return $dv&&$dv.Oa?$dv.Oa.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Na(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ua=function(){return!1};return!1};this.Na=function(a){a.$sf.ext.geom&&(this.Na="function"==typeof a.$sf.ext.geom?
function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Na(a)};this.v=function(a,f){if(null!=a&&null!=f)for(var b in f)f.hasOwnProperty(b)&&(a[b]=f[b])};this.kc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.wb=function(){var a=!1;if(1==this.za("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.xb=function(a,f,b){var k=b&&b.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(b&&b.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
f.Y===k.Safari&&(null===f.ta||void 0===f.ta||!/^[3-8]/.test(f.ta)))return this.xb=function(){return!0},!0;this.xb=function(){return!1};return!1};this.za=function(a){var f,b=this.Mc();b&&b.AVO&&(f=b.AVO[a]);return f};this.Mc=function(){var a={},f=window.$dv,b=window.$uid;f.tags&&f.tags[b]&&(a=f.tags[b]);return a};this.Hb=function(){return 1==this.za("sam")?!0:!1};this.Xa=function(a){return a.document.hasFocus()};this.Ma=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(f,
b,k,n,p){if("undefined"==typeof n||null==n)n=window;n.addEventListener(f,b,k);p&&a.cache.push([f,b,k,n])}:window.attachEvent?a.add=function(f,b,k,n,p){if("undefined"==typeof n||null==n)n=window;n["e"+f+b]=b;n[f+b]=function(){n["e"+f+b](window.event)};n.attachEvent("on"+f,n[f+b]);p&&a.cache.push([f,b,k,n])}:a.add=function(){};window.removeEventListener?a.remove=function(a,b,k,n){if("undefined"==typeof n||null==n)n=window;n.removeEventListener(a,b,k)}:window.detachEvent?a.remove=function(a,b,k,n){if("undefined"==
typeof n||null==n)n=window;n.detachEvent("on"+a,n[a+b]);n[a+b]=null;n["e"+a+b]=null}:a.remove=function(){};a.flush=function(){for(var f=0;f<a.cache.length;f++)a.remove.apply(a,a.cache[f]);a.cache=[]}};this.getElementsByClassName=function(a,f){return a.getElementsByClassName?a.getElementsByClassName(f):a.querySelectorAll?a.querySelectorAll("."+f):[]};this.Ya=function(){var a=!1;if($dv&&$dv.CommonData){var f=$dv.CommonData.detectedDeliveryType;f&&0!=f?a=2==f||3==f:(f=$dv.CommonData.deviceType)&&(a=
2==f||3==f)}return a};this.ve=function(a,f){var b=a||"",k="";if(f&&(b+=": "+(f.message||""),f.stack)){var k=f.stack||"",n=k.indexOf("at ");0>n&&(n=0);k=", Stack: "+k.slice(n,k.length)}b=b.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");k=k.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");n=null;try{n=encodeURIComponent(b+k).slice(0,500)}catch(p){try{n=encodeURIComponent(b).slice(0,500)}catch(r){n=
b.slice(0,500)}}return n}}
function ba(a,f,b,k,n,p){var r=new S;this.f=k;this.window=b;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.jc=null;this.N={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.R=n;this.W=this.dvObj.Enums.TrafficScenario;this.U=f;this.A=p.A;115==this.dataObj.hb&&(this.A.C.h=20,this.A.C.w=20);this.df=function(){p.$e(this.c);this.c=null};var q=[],t=["object","embed","img","iframe"];this.dataObj.spotXmode&&(t=["object","embed",
"video","iframe"]);this.Ne=function(a){r.a("a33");a=r.da(a);return this.Oe(a)};this.Oe=function(a){if(a){var b=a.w;a=a.h;for(var l=f.length,k=0,h=0;h<l;h++)if(15>=Math.abs(b-f[h].w))for(var k=f[h].h.length,d=0;d<k;d++)if(15>=Math.abs(a-f[h].h[d]))return!0}return!1};this.qe=function(){r.a("a34");return this.re()||this.gf()};this.gf=function(){r.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=[],f=window.parent;r.a("ff6");try{b=f.document.getElementsByTagName("script")}catch(h){}r.a("ff6e");
for(var f=b.length,k=0;k<f;k++)if(b[k]&&b[k].id&&b[k].id.substr(7)==a)return b[k];return null};this.re=function(){r.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ud=function(a){r.a("a38");var b={node:a,La:0};a=[];for(q=[];b||0<a.length;){try{var f;a:{var k=b.node;try{if(k&&-1!=t.indexOf(k.nodeName.toLowerCase())){f=!0;break a}}catch(n){}f=!1}if(f&&this.Ne(b.node)&&
!p.pa(b.node)&&p.S(b.node))return b;if(b.La<=this.A.Xe){var h,d=b.node,e=b.La,b=[],g=d.parentNode;g&&-1==q.indexOf(g)&&(q.push(g),b.push({node:g,La:e+1}));if(d.hasChildNodes())for(var v=0;v<d.childNodes.length;v++)d.childNodes[v]&&-1==q.indexOf(d.childNodes[v])&&1===d.childNodes[v].nodeType&&(q.push(d.childNodes[v]),b.push({node:d.childNodes[v],La:e+1}));var x,z=d,D=[],u=null;z&&z.parentNode&&(u=z.parentNode.firstChild);for(;u;)1===u.nodeType&&u!==z&&D.push(u),u=u.nextElementSibling||u.nextSibling;
x=D;for(v=0;v<x.length;v++)x[v]&&-1==q.indexOf(x[v])&&1===x[v].nodeType&&(q.push(x[v]),b.push({node:x[v],La:e+1}));if(h=b)for(b=0;b<h.length;b++)a.push(h[b])}}catch(n){}b=a.shift()}return{node:null}};this.ye=function(){r.a("a37");var a=this.qe(),b=null;a&&(b=this.Ud(a));return b};this.ie=function(a){r.a("a31");if(this.c=p.xe())return this.f.wd(),this.jc=!0,this.c;if(this.dataObj.btreg&&0<this.dataObj.btreg.length&&!0===this.jc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&(a=this.ye())&&a.node&&
(this.f.vd(a.La),this.c=a.node);return this.c};return this}
function ca(a,f,b,k,n,p){function r(a,c){for(var e=[],g=0;g<w.length;g++){var b=[],b=c(a,w[g]),f=m.ma(b);if(0!=f){var k=m.Sc(w[g]);if(null!=k)for(var l=0;l<f;l++)try{b[l].sb=k,e.push(b[l])}catch(n){}}}return e}function q(a){var c=null;if("celtra-ad-v3"==a.className)a.celtra&&1==a.celtra.loaded&&(c=a.celtra.viewabilityObservee);else{a=m.getElementsByClassName(a,"celtra-ad-v3");for(var e=m.ma(a),g=0;g<e;g++){var b=a[g];if(b&&b.celtra&&1==b.celtra.loaded){c=b.celtra.viewabilityObservee;break}}}c&&(c.sb=
m.Sc(c.ownerDocument)||window);return c}function t(a,c){return r(a,function(e,a){m.a("ff4");var h=a.getElementsByTagName(e);m.a("ff4e");return"1"!=c?h:m.gc(h)})}var c=this,m=new S,l="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=f;this.c=b;this.R=k;this.W=n;this.dvObj=void 0===p?p={}:p;this.A={C:{h:1,w:1},Af:{h:10,w:10},Xe:10};115==this.dataObj.hb&&(this.A.C.h=20,this.A.C.w=20);this.Ae=function(a){if(a.scanOrder)return a.scanOrder;var c=[1==l?"object":"embed",1==l?"embed":
"object","href","img","span","iframe","frameElement","div"];a.findclass&&1==a.findclass&&c.push("classDeclaration");a.jb&&0<a.jb.length&&c.unshift("searchCustomElementsFromTag");return c};this.searchCustomElementsFromTag=function(a){for(var d=0;d<a.jb.length&&(c.Ic(a.jb[d],a),!c.c);d++);};this.Jb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.be=function(){var h=c.dataObj.mb+"-"+c.dataObj.lb;a.isBrandShieldOrigin&&
(h+="-bs");return h.replace(RegExp(",","g"),";")};this.rc=this.be();this.Ic=function(a,d){if(!(1>d.btreg.length))for(var e=t(a,d.displaynon),g=m.ma(e),b=0;b<g;b++)if(e[b]&&c.xa(d,e[b],!0)&&!c.pa(e[b])){var f=m.da(e[b]);if(f&&f.h>c.A.C.h&&f.w>c.A.C.w&&c.S(e[b])){c.c=e[b];break}var l=m.Kb(e[b],c.A.C.w,c.A.C.h,m.Xb(m.da,m));if(l&&c.S(l)){c.c=l;c.S(e[b]);break}if((l=q(e[b]))&&(f=m.da(l))&&f.h>c.A.C.h&&f.w>c.A.C.w&&c.S(l)){c.c=l;c.S(e[b]);break}}};this.div=function(a){this.Ic("div",a)};this.span=function(a){m.a("a10");
if(!(1>a.btreg.length))for(var d=t("span",a.displaynon),e=m.ma(d),g=0;g<e;g++)if(d[g]&&c.xa(a,d[g],!0)&&!c.pa(d[g])){var b=d[g];m.a("a20");if(b&&"1"==b.getAttribute("adunit")){c.c=d[g];break}if((b=m.Kb(d[g],c.A.C.w,c.A.C.h,m.Xb(m.da,m)))&&c.S(b)){c.c=b;c.S(d[g]);break}if(b=q(d[g])){var f=m.da(b);if(f&&f.h>c.A.C.h&&f.w>c.A.C.w&&c.S(b)){c.c=b;c.S(d[g]);break}}}};this.object=function(a){m.a("a11");for(var d=t("object",a.displaynon),e=m.ma(d),g=0;g<e;g++)if(d[g]&&c.xa(a,d[g])&&!c.pa(d[g])){var b=m.Kb(d[g],
c.A.C.w,c.A.C.h,m.Xb(m.da,m));if(b&&c.S(b)){c.S(d[g]);c.c=b;break}}};this.embed=function(a){m.a("a12");for(var d=t("embed",a.displaynon),e=m.ma(d),g=0;g<e;g++)if(d[g]&&c.xa(a,d[g])&&!c.pa(d[g])){var b=m.da(d[g]);if(b&&b.h>c.A.C.h&&b.w>c.A.C.w&&c.S(d[g])){c.c=d[g];break}}};this.href=function(a){m.a("a13");for(var d=t("a",a.displaynon),e=m.ma(d),g=0;g<e;g++)if(d[g]&&c.xa(a,d[g])&&!c.pa(d[g])){var b=d[g].getElementsByTagName("img");if(0<b.length){var f=m.da(b[0]);if(f&&f.h>c.A.C.h&&f.w>c.A.C.w&&c.S(d[g])){c.c=
b[0];break}}}};this.img=function(a){m.a("a14");for(var d=t("img",a.displaynon),e=m.ma(d),g=0;g<e;g++)if(d[g]&&c.xa(a,d[g])&&0>d[g].src.indexOf("event")&&!c.pa(d[g])){var b=m.da(d[g]);if(b&&b.h>c.A.C.h&&b.w>c.A.C.w&&c.S(d[g])){c.c=d[g];break}}};this.classDeclaration=function(a){m.a("a9");var d="undefined"!==typeof window.document.getElementsByClassName,e="undefined"!==typeof window.document.querySelectorAll;if(!(1>a.btreg.length)){var g=[];if(d)g=c.getElementsByClassName(a.btreg,a.displaynon);else if(e)g=
c.querySelectorAll(a.btreg,a.displaynon);else return;a=m.ma(g);for(d=0;d<a;d++)if(g[d]&&!c.pa(g[d])&&(e=m.da(g[d]))&&e.h>c.A.C.h&&e.w>c.A.C.w&&c.S(g[d])){c.c=g[d];break}}};this.iframe=function(a){m.a("a15");for(var d=t("iframe",a.displaynon),e=m.ma(d),g=0;g<e&&!c.zc(a,d[g]);g++);};this.frameElement=function(a){try{m.a("a16"),k==n.SameDomain&&c.zc(a,window.frameElement)}catch(d){}};this.getElementsByClassName=function(a,c){return r(a,function(e,a){m.a("ff1");var b=a.getElementsByClassName(e);m.a("ff1e");
return"1"!=c?b:m.gc(b)})};this.querySelectorAll=function(a,c){return r(a,function(e,a){m.a("ff3");var b=a.querySelectorAll("."+e);m.a("ff3e");return"1"!=c?b:m.gc(b)})};this.ka=function(a,b){m.a("a28");return!a||!b||5>b.length?!1:null!=(c.xc?c.xc(a,b):c.Lb(a,b))?!0:c.Yb&&"function"===typeof c.Yb?c.Yb(a,b):!1};this.xa=function(a,b,e){m.a("a22");var g=null;return a.btreg&&0<a.btreg.length&&(c.xc=1==a.Re?c.Cd:c.Lb,g=c.Id(a,b,e))||!c.c&&(g=c.Jd(a,b))?!0:!1};this.Od=function(a){m.a("a21");if(a&&!c.pa(a)){var b=
m.da(a);if(b&&b.h>c.A.C.h&&b.w>c.A.C.w&&c.S(a))return c.c=a,!0}return!1};this.zc=function(a,b){m.a("a17");return c.xa(a,b)?c.Od(b):!1};this.pa=function(a){m.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==c.rc)return!0}return!1};this.S=function(a){m.a("a18");if(a&&0==c.pa(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",b+","+c.rc):(m.a("ff5"),b=window.document.createAttribute("dvvisit"),m.a("ff5e"),b.value=c.rc,a.setAttributeNode(b));
return!0}catch(e){}return!1};this.$e=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Cd=function(a,b){m.a("a29");var e;try{e=(new RegExp(b)).exec(a)}catch(g){e=c.Lb(a,b)}return e};this.Lb=function(a,c){m.a("a30");var e=null;-1!==a.indexOf(c)&&(e=a);return e};var w=[];this.Id=function(a,b,e){m.a("a23");var g;try{if(a.Gc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(g=c.ka(b.id,a.btreg))||(g=c.ka(b.src,a.btreg));g||(g=c.ka(b.href,a.btreg));g||(g=
c.ka(b.getAttribute("flashvars"),a.btreg));g||(g=c.ka(b.name,a.btreg));!g&&a.findclass&&1==a.findclass&&(g=c.ka(b.getAttribute("class"),a.btreg));if(!g&&c.dataObj.Ka&&0<c.dataObj.Ka.length)for(var f=c.dataObj.Ka,l=0;l<f.length&&!(g=c.ka(b.getAttribute(f[l]),a.btreg));l++);g||e||(g=c.ka(b.innerHTML,a.btreg));g&&!e&&(g=c.Hd(a,b));return g}catch(k){return g}};this.Fa=function(a,b){m.a("a25");if(!a)return!1;a=a.toLowerCase();for(var e=0;e<c.Jb.length;e++){var g;if(b.Ac&&(g=(c.Jb[e][0]+b.Ac).toLowerCase(),
g=a.indexOf(g),-1<g)||b.dd&&(g=(c.Jb[e][0]+b.dd).toLowerCase(),g=a.indexOf(g),-1<g))return!0}return!1};this.Jd=function(a,b){m.a("a24");var e;try{if(a.Gc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(e=c.Fa(b.id,a))||(e=c.Fa(b.src,a));e||(e=c.Fa(b.href,a));e||(e=c.Fa(b.Ff,a));e||(e=c.Fa(b.name,a));e||(e=c.Fa(b.innerHTML,a));if(!e&&c.dataObj.Ka&&0<c.dataObj.Ka.length)for(var g=c.dataObj.Ka,f=0;f<g.length&&!(e=c.ka(b.getAttribute(g[f]),a.btreg));f++);return e}catch(l){return e}};this.Hd=function(a,
b){m.a("a26");return null==a.Ua||""==a.Ua?!1:c.ka(c.Bd(b),a.Ua)};this.searchByAdSrvId_8=function(a,b){m.a("a1");var e=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=e&&(e=e.toString(),e.replace(RegExp("-","g"),"")==b)?!0:!1};this.Yb=this["searchByAdSrvId_"+(c.dataObj?c.dataObj.hb||"":"")];this.Bd=function(a){m.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,e="",c=0;c<b;c++)e=e+a.attributes[c].nodeName+"="+a.attributes[c].nodeValue+" ";return e+a.innerHTML};this.xe=function(){m.a("32");
var a=[];void 0===p.tags&&(p.tags={});void 0===p.tags[$uid]&&(p.tags[$uid]={});void 0!==p.tags[$uid].spvi&&(a.push(p.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));c.dataObj.scanOrder=this.Ae(c.dataObj);a.push(c.dataObj);var d=c.window,e=0,g=[];try{do{g.push(d.document);for(var f=g,l=d.document.getElementsByTagName("iframe")||[],k=0;k<l.length||25>k;k++){var n=null,n=m.te(l[k]);void 0!==n&&null!==n&&0==m.Ke(n,f)&&f.push(n)}d=m.ne(d)}while(d&&10>++e)}catch(q){}w=
g;for(d=0;d<a.length;d++)for(e=a[d],g=0;g<e.scanOrder.length;g++)if(void 0!=c[e.scanOrder[g]]&&(c[e.scanOrder[g]](e),c.c))return c.c;return b};return this}
function dv_CustomClientViewAssureService(a){function f(a){a&&($dv.registerEventCall($uid,{dvp_gmlad:1}),f=function(){})}function b(a){return{settings:a.settings,buckets:0,reported:!1,eventId:a.eventId,Ra:a.Ra,nb:a.nb,mc:a.mc}}this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new S;var k=[],n=null,p=null,r=null,q=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(n=this.dvObj.tags[this.impressionId].cvmSettings,p=this.dvObj.tags[this.impressionId].billable,
r=this.dvObj.tags[this.impressionId].bprjct,q=this.dvObj.tags[this.impressionId].gmmod);this.uc=window.dv_cvmSettings||n||a.cvmSettings;this.Ub=window.dv_billable||p||a.billable;this.Fc=window.If||r||a.bprjct;this.Tc=window.Kf||q;this.ce=new b({settings:this.uc,eventId:6,Ra:["CustomViewabilityViewable"]});var t=this.b.za("rpv"),n=this.b.Mc().bgm;a.zb=1==t&&1==n;this.Ec=new b({settings:this.Ub,eventId:17,Ra:a.zb?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],nb:!0,
mc:!0});this.uc&&k.push(this.ce);this.Ub&&k.push(this.Ec);a.ya=a.ya||[];n={serverProperties:{projected:"bp",viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Fc&&(n={serverData:this.Fc,projectionData:n,reportRTN:!0},a.ya.push(n));n={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",
viewrate:"modgmvr",error:"modgmer"}};this.Tc&&(n={serverData:this.Tc,projectionData:n,reportRTN:!0},a.ya.push(n));this.Td=dv_InViewService;this.Td(a);var c=this.Mb;this.Mb=function(a){a=c(a);for(var b=0;b<k.length;b++){var f=this.Ge(a,k[b]);this.vf(f,k[b]);this.Qd(k[b])}return a};var m=this.Sa;this.Sa=function(a,b){m(a,b);this.Ub&&1==this.Zb&&(this.va(["BillableMeasuredImpression"]),t?0==this.dataObj.zb&&this.va(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.va(["GroupMMeasuredImpression"]))};
this.Ge=function(a,b){"undefined"===typeof b.settings.focus||b.settings.focus||(a.g=a.ja);return a};this.vf=function(a,b){(!b.settings.measureType||"consecutive"==String(b.settings.measureType).toLowerCase())&&a.g<b.settings.adArea?b.buckets=0:a.g>=b.settings.adArea&&(!b.nb||1!=this.dataObj.irtf)&&(b.buckets+=this.ca.interval);var c=0,d=0;a.B&&a.B.i&&(c=a.B.i.m||0,d=a.B.i.o||0);b.M=this.oa.Wb(c,d,b.mc);f(b.M)};this.Qd=function(a){a.cf||a.nb&&1==this.dataObj.irtf||!(this.Kd(a)||a===this.Ec&&a.settings&&
!a.settings.doNotReportViewedOnLargeAd&&a.M)||(this.ea.aa(a.eventId),a.Ra&&this.va(a.Ra),a.cf=!0)};this.Kd=function(a){return a.buckets>=a.settings.duration?!0:!1}}
function dv_InViewService(a){function f(){null===p.interval&&(p.interval=setInterval(p.ue(),p.ca.interval))}function b(){if(!1===p.ad){p.ad=!0;try{p.b.Ma.remove("load",arguments.callee,!1,element)}catch(a){}p.Db();p.b.a("s41");p.oa=new aa(p.Xd?p.Xd:p.window,p.c,p.R,p.N,p.O,p.f.Hc,p.dvObj,p.impressionId);p.b.a("s42");p.Ed();p.start()}}function k(a,b){return a.isReportingDisabled?new U:new T(a,b)}function n(a,b){p.b.Ma.add("click",function(){p.Qb(!0);$dv.registerEventCall(p.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});p.b.Ma.remove("click",arguments.callee,!1,a)},!1,a,!1)}var p=this;this.cd=10;this.Sd=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"658";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new S;this.He=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.ad=!1;var r={serverProperties:{projected:"p",
error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},q=!1,t=!1;this.ya=a.ya||[];(this.wf=a.prjct)&&this.ya.push({serverData:a.prjct,projectionData:r,Jf:!0,Pf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],Gf:["MeasurementCapabilityDetected","ProjectedMeasured"]});r={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},
reportQueryString:{projected:"isuprjct",measurems:"isumms",viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.ya.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:r});this.De=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,
a=a.substring(a.indexOf("?")+1));return a};this.Rc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.V=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.Ee=function(){var a=this.V("uid",this.ba);null==a?(a=this.Rc(),this.ba=this.ba+"&uid="+a):""==a&&(a=this.Rc(),this.ba=this.ba.replace("&uid=","&uid="+a));return a};this.pc=function(a,b,c,d){if(d&&d.insertBefore&&
d.firstChild&&(a=this.window.document.createElement(a))){for(var f in b)a[f]=b[f];for(f in c)a.style[f]=c[f];d.insertBefore(a,d.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.R=this.dvObj.CommonData.Scenario||this.Wd();this.N={Y:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Z=
this.dvObj.Enums.BrowserId;this.W=this.dvObj.Enums.TrafficScenario;this.ab="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.tc=this.Ta=!1;this.lc=!0;this.interval=null;this.ba=this.He();this.Da=this.De();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.ca=window.fe||this.window.fe||{interval:100,Ba:{"default":{time:null,Ma:["beforeunload","unload"],rd:9E5}}};this.fd={};var c=null;this.T=window.ee||this.window.ee||{interval:1E3,
$:6};r=a&&a.td?a.td:!1;a=a&&a.ud?a.ud:!1;!1!==r&&!1!==a&&(this.T.interval=r,this.T.$=a,$dv.registerEventCall(this.impressionId,{Df:this.T.interval,Ef:this.T.$}));a=this.b.Ya();this.$d={kb:12,ac:10,$a:30};this.O={Firefox:{X:115},Chrome:{X:89},Safari:{X:38},Explorer:{X:55},Ye:500,Ya:a,$a:30};var m=!1,l=0,w=[5,10,15];window.devicePixelRatio&&(this.O.Firefox.X=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&
this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.U=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},
{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,120]},{w:900,h:[240]}];this.dataObj.spotXmode&&(this.U.push({w:320,h:[240]}),this.U.push({w:400,h:[300]}),this.U.push({w:450,h:[338]}),this.U.push({w:600,h:[800]}),this.U.push({w:640,
h:[360]}),this.U.push({w:854,h:[480]}),this.U.push({w:500,h:[375]}));a&&(this.U.push({w:320,h:[50,100,480]}),this.U.push({w:300,h:[50,31]}),this.U.push({w:120,h:[20]}),this.U.push({w:168,h:[28]}),this.U.push({w:216,h:[36]}),this.U.push({w:292,h:[30]}));this.rb=this.Ee();this.$b=!1;this.Qa=function(a,b){this.window.Jc||(this.window.Jc=[]);this.window.Jc.push({caller:a,Hf:b})};this.startTime=(new Date).getTime();this.Pd=4;this.yc=0;this.hc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,
beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Bf:17,interval:32};this.Zb=!1;this.sd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.f.oe();this.window.dv_logObject[this.rb]=a}this.b.a("ie16e")};this.Gb=function(a){this.b.a("ie17");this.Gb=this.$b?function(a){this.f.md(a);this.sd()}:function(a){this.f.md(a)};this.Gb(a)};this.sc=function(a,b){this.sc=this.$b?function(a,e){this.f.ld(a,e);this.sd()}:function(a,e){this.f.ld(a,e)};this.sc(a,b)};this.Db=
function(){this.b.a("s4");this.c=this.Tb.ie(this.T.$);!this.c&&this.R==this.W.CrossDomain&&this.b.ua(this.window)&&(this.T.$=0);if(this.c)this.hf(),this.f.af(this.c),q||(n(this.c,"ad"),q=!0),t||this.R!=this.W.CrossDomain&&this.R!=this.W.SameDomain||(n(window.parent,"ifr"),t=!0),setTimeout(f,this.Tb.jc?10:50);else if(0<this.T.$)this.T.$--,this.jf(),setTimeout(this.je(),this.T.interval);else{try{this.R==this.W.CrossDomain&&(this.b.bd(this.window,this.U)||this.b.ua(this.window))?(this.c=this.b.Aa(this.window),
this.f.kd()):this.R==this.W.SameDomain&&this.b.bd(this.window,this.U)?(this.c=this.b.Aa(window.parent),this.f.kd(),this.Zd()):this.T.$=-1}catch(a){this.T.$=-1}setTimeout(f,10)}this.b.a("s4e")};this.Zd=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.c=b[d],this.window=a.parent);this.b.a("ff26e")};this.jf=function(){this.dataObj.btreg&&this.dataObj.Ua?this.f.nf():
this.f.pf()};this.hf=function(){this.b.a("s9");this.Ta=!0;this.f.kf();this.b.a("s9e")};this.Rd=function(){this.dataObj.hb=this.V("adsrv",this.ba)||"";this.dataObj.btreg=this.V("btreg",this.ba)||"";this.dataObj.dd=this.V("plcid",this.ba)||"";"8"==this.dataObj.hb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Ua=this.V("btadsrv",this.ba)||"";this.dataObj.Ac=this.V("adid",this.ba)||"";this.dataObj.rb=this.rb;this.dataObj.Re=this.V("isbtregex",this.Da)||"";this.dataObj.mb=
this.V("ctx",this.ba)||"";this.dataObj.lb=this.V("cmp",this.ba)||"";this.dataObj.Te=this.V("lomd",this.Da)||"";this.dataObj.findclass=this.V("findclass",this.Da)||"";this.dataObj.displaynon=this.V("displaynon",this.Da)||"";this.dataObj.Gc=this.V("bsdvview",this.Da)||"";var a=this.V("bttag",this.Da)||"";this.dataObj.jb=0<a.length?a.split("|"):[];a=this.V("btattb",this.Da)||"";this.dataObj.Ka=0<a.length?a.split("|"):[]};this.ed=function(a){a=this.va(a);return 0<a.length?{tagServiceResult:a.join(",")}:
{}};this.va=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d)}return b};this.xd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ba+="&TKH="+this.dataObj.serverSettings.TKH)};this.de=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),
d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.de();this.xd();this.Rd();this.f=new H(this.Sd,this.$d,this.dataObj);this.ea=k(this.dataObj,this.f);this.dataObj.isRTNsDisabled&&(this.va=function(){return[]});this.$b=this.window.dv_logObject?!0:!1;this.qf();this.Vd=new ca(this.dataObj,this.window,this.c,
this.R,this.W,this.dvObj);this.Tb=new ba(this.dataObj,this.U,this.window,this.f,this.R,this.Vd);var a=window.parent;"589953"==this.dataObj.mb&&"587351"==this.dataObj.lb||"589953"==this.dataObj.mb&&"616389"==this.dataObj.lb||"polite"==this.dataObj.Te?(setTimeout(b,15E3),this.b.Ma.add("load",function(){setTimeout(b,1E3)},!1,a,!1)):b()}catch(c){var d=this;this.Ga(function(){d.Qa("inViewManager",c);d.f.cb("inViewManager",c);d.ea.aa(d.logEvents.errorlevel1)},"inViewManager",c)}};this.eb=function(a){this.b.a("ie20");
-6!=a.g&&(-3==a.g||-5!=a.g&&0>a.g&&-1==this.T.$)&&(this.vc(),this.eb=function(){})};this.vc=function(){this.ea.aa(this.logEvents.nonMeasurable);this.va(["ImpressionNotMeasured"]);this.vc=function(){}};this.Sa=function(a,b){a.b.a("ie21");if(0<=b.g||-5==b.g&&-1>=a.T.$){if(a.dvObj&&a.impressionId){a.b.a("ie23");var c=a.ed(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");a.ea.aa(a.logEvents.startMeasure,c)}else a.ea.aa(a.logEvents.startMeasure);a.Zb=!0;a.Sa=function(){};a.eb=function(){}}a.b.a("ie22")};
this.Qb=function(a){this.b.a("ie25");if(this.f.Nc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.ed(["IabView","GeoViewed"]),this.b.a("ie29"),this.ea.aa(this.logEvents.iabViewable,a)):this.ea.aa(this.logEvents.iabViewable),m=!0,this.Qb=function(){};this.b.a("ie26")};this.ae=function(a){if(m&&this.f.Nc())for(l+=a,a=0;a<w.length;a++)null!=w[a]&&l>=1E3*w[a]&&(this.va(["Viewed"+w[a]+"Sec"]),w[a]=null);else l=0};var h="hidden",d=0;this.hasFocus=function(){vis=["hidden",
"webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){h=vis[a];break}a=1==this.b.za("fcs");var b=!1;try{this.b.Xa(this.window),b=!0}catch(c){}var f=!1;try{this.b.Xa(this.window.top),f=!0}catch(c){}var k=null,k=a&&b&&this.N.Y==this.Z.IE?function(){var a=p.b.Xa(p.window);p.R==p.W.OnPage&&(a=a&&p.lc);return a}:a&&f?function(){var a=!0,a=p.b.Xa(p.window.top);p.R==p.W.OnPage&&(a=a&&p.lc);return a}:"undefined"!==typeof document[h]?function(){return!p.window.document[h]}:
f?function(){return p.b.Xa(p.window.top)}:function(){return!0};this.hasFocus=function(){try{return k()}catch(a){d++,5<=d&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.fc=function(a){var b=a.oa.se();a.b.a("ie12");0>b.g&&this.f.Fb(Math.abs(b.g));null==this.c||-3==b.g||a.hasFocus()||(b.g=0,this.f.Fb(9));a.b.a("ie13");return c=b};this.Mb=function(a){a.b.a("ie1");var b=a.c?a.c.sb||a.window:a.window;a.oa.c=a.c;a.oa.window=b;a.b.a("ie2");b=a.fc(a);a.Ta&&(-1==b.g||-2==b.g)&&
-1<=a.T.$&&(a.hd(a),a.Db());a.b.a("ie3");-5==b.g&&(a.T.$--,a.f.nd(),a.Pa||(a.Pa=function(b){b=a.oa.vb(b);a.f.bb(b)}));a.b.a("ie4");a.Pa&&0<b.g&&(a.Pa(b),a.Pa=null);a.b.a("ie5");if(a.Ta&&!a.tc){a.tc=!0;var c=a.oa.vb(b);a.f.bb(c)}-5==b.g&&-1<=a.T.$&&(a.hd(a),a.Db(),b=a.fc(a),-5==b.g&&0<a.T.$&&a.f.ef());a.b.a("ie6");a.sc(b,a.ca.interval);a.b.a("ie7");a.Gb(b);a.b.a("ie8");a.f.pd(b.ga);a.eb(b);a.b.a("ie9");a.Sa(a,b);a.b.a("ie10");a.Qb();a.b.a("ie11");a.ae(a.ca.interval);a.b.a("ie12");return b};this.hd=
function(a){a.Ta=!1;a.c=null;a.Tb.df();a.oa.Ie()};this.ue=function(){this.b.a("s26");var a=this;return function(){try{a.Mb(a)}catch(b){a.Ga(function(){a.yc<a.Pd&&(a.yc++,a.Qa("getIntervalCallback",b),a.f.cb("getIntervalCallback",b),a.ea.aa(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Qc=function(a){var b=this;return function(){b.Ga(function(){b.ea.aa(b.logEvents[a])},"getReportEventCallback")}};this.je=function(){var a=this;return function(){a.Ga(function(){a.Db();a.c||a.f.Eb()},"getAdLocateCallback")}};
this.Wa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ga(function(){a.Qa("getFocBluEventCallback",c);a.f.cb("getFocBluEventCallback",c);a.ea.aa(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Dd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.f.pe().slice(0),c=0;c<b.length;c++)void 0===
b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Zb,totalPageTime:(a.f.dc()-a.f.Ce())/1E3,notApplicableTime:a.f.Pc()/1E3}}catch(f){return{}}}}}catch(b){}};this.Ed=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=
function(){var a={};a.perc=c.g;0<=c.g&&c.B&&c.B.i&&(a.adWidth=c.B.i.o,a.adHeight=c.B.i.m);return a};a.VA.getAdElem=function(){return p.c}}}catch(b){}};this.Dd();this.start=function(){this.b.a("s35");this.Ze(this);var a;this.ca&&this.ca.Ba&&this.ca.Ba[this.ab]&&(a=this.ca.Ba[this.ab].Ma);if(a)for(var b=a.length,c=0;c<b;c++)this.fd[a[c]]=this.Qc(a[c]),this.Ja(this.window,a[c],this.fd[a[c]]);this.sf();this.ca&&this.ca.Ba&&this.ca.Ba[this.ab]&&this.ca.Ba[this.ab].rd&&setTimeout(this.bf(),this.ca.Ba[this.ab].rd)};
this.bf=function(){var a=this;return function(){a.Qc("timeout")();clearInterval(a.interval);a.ea.aa=function(){}}};this.Ze=function(a){try{var b=a.fc(a);-5==b.g&&(this.f.nd(),this.Pa||(this.Pa=function(b){b=a.oa.vb(b);a.f.bb(b)}));if(a.Ta)if(this.tc=!0,-5!=b.g){var c=a.oa.vb(b);a.f.bb(c)}else a.f.bb("true");a.f.pd(b.ga);var d=a.oa.le(b,a.f.Pc());a.f.mf(d);a.f.od(b.g);a.Gb(b);a.eb(b);a.Sa(a,b)}catch(f){a.Ga(function(){a.Qa("onStartReport",f);a.f.cb("onStartReport",f);a.ea.aa(a.logEvents.errorlevel1)},
"onStartReport",f)}};this.sf=function(){this.Ja(this.window,"blur",this.Wa());this.Ja(this.window,"focus",this.Wa());this.Ja(this.window.document,"click",this.Wa());this.Ja(this.window.document,"mousedown",this.Wa());this.Ja(this.window.document,"mouseup",this.Wa())};this.Ja=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=
function(){};this.qf=function(){this.b.a("ff24");this.R==this.W.CrossDomain?this.b.ua(this.window)||this.b.kc(this.window)||this.b.wb()||this.b.xb(this.R,this.N,this.dvObj)||(this.N.Y!=this.Z.Firefox&&this.N.Y!=this.Z.IE?this.f.rf():this.N.Y==this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.f.qc()):window.document.body.getBoundingClientRect||this.f.qc();this.hc=this.f.Hc();this.b.a("ff24e")};this.Ga=function(a,b,c){try{a()}catch(d){try{0<this.cd&&(this.cd--,a=c||d,b=b||"unknown caller",
this.Qa(b,a),this.f.cb(b,a),this.ea.aa(p.logEvents.errorlevel1))}catch(f){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||a.cvmSettings||a.billable?(new dv_CustomClientViewAssureService(a)).inViewManager():(new dv_InViewService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=
Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs658");if(tagObject){var serviceParams=tagObject.services.avs658;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
